### ISSUE TITLE
Update conventions diagram to reflect the new name for this repository

### ISSUE THREAD

**Issue by ndiego** [WordPress/block-development-examples#100]
The diagram mentioned in [Conventions for examples](https://github.com/WordPress/block-development-examples/wiki/06-Conventions-for-examples) still references the old name "Gutenberg Examples". It would be nice to get this updated, but not sure how to access the original file. Would you be able to update this @juanmaguitar?

**Comment by juanmaguitar** [comment]
> Would you be able to update this @juanmaguitar?

Done ✅

> but not sure how to access the original file

For future reference, each Excalidraw diagram can be directly edited and exported to a new link referencing the new version (that's what I did in this case)
