### ISSUE TITLE
Add editable-block-no-build example

### ISSUE THREAD

**Issue by cweiske** [WordPress/block-development-examples#113]
It would be nice if there was an example for an editable block that requires no build step, just as there is `minimal-block-no-build-e621a6`.

**Comment by juanmaguitar** [comment]
Hey @cweiske! 👋 Thanks for the suggestion. 
An editable block that requires no build step example has been added to `editable-block-1b8c51`
See [code](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/editable-block-1b8c51/src/blocks/basic-editable-block-no-build-1b8c51) and  [live demo](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/WordPress/block-development-examples/trunk/plugins/editable-block-1b8c51/_playground/blueprint.json)

**Comment by cweiske** [comment]
Thank you so much!
