### ISSUE TITLE
Add "copyright-date-block" example

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/block-development-examples#17]
A simple WordPress block plugin that utilizes both a `render.php` file and a `save.js` file. On the front end, the `render.php` file takes precedence, but if the plugin is ever disabled, the `save.js` file serves as a fallback, so a copyright date is still displayed.

https://github.com/ndiego/copyright-date-block

**Comment by ryanwelcher** [comment]
@ndiego @juanmaguitar has this been completed?

**Comment by juanmaguitar** [comment]
Yes, It's been done here https://github.com/WordPress/block-development-examples/pull/67
I close this issue
