### ISSUE TITLE
Create core-data-basics-XXXXXX example

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/block-development-examples#22]
Migrate the [existing example](https://github.com/WordPress/gutenberg-examples/tree/trunk/non-block-examples/09-code-data-basics-esnext) from the current repo

**Comment by juanmaguitar** [comment]
I think this example has been already migrated to [non-block-react-wp-data-56d6f3](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/non-block-react-wp-data-56d6f3)

**Comment by juanmaguitar** [comment]
> I think this example has been already migrated to [non-block-react-wp-data-56d6f3](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/non-block-react-wp-data-56d6f3)

No, it's not. It's a different example. I have opened https://github.com/WordPress/block-development-examples/pull/56 to migrate this example

**Comment by juanmaguitar** [comment]
Closed as per https://github.com/WordPress/block-development-examples/pull/56
