### ISSUE TITLE
Create editable-xxxx

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/block-development-examples#33]
Migrate from [03-editable-esnext ](https://github.com/WordPress/gutenberg-examples/tree/trunk/blocks-jsx/03-editable-esnext)

**Comment by juanmaguitar** [comment]
Already migrated [editable-block-1b8c51](https://github.com/wordpress-juanmaguitar/wp-block-development-examples/tree/trunk/plugins/editable-block-1b8c51)
