### ISSUE TITLE
Broken links in Data Basics example

### ISSUE THREAD

**Issue by leewillis77** [WordPress/block-development-examples#79]
The Data Basic example (https://github.com/WordPress/block-development-examples/tree/trunk/plugins/data-basics-59c8f8) has a number of links at the bottom of the README under "Related resources". 

Several of these are broken:
https://developer.wordpress.org/block-editor/reference-guide/packages/packages-_data/
https://developer.wordpress.org/block-editor/reference-guide/packages/packages-_data/#useselect
https://developer.wordpress.org/news/2023/05/useentityrecords-an-easier-way-to-fetch-wordpress-_data/

**Comment by ryanwelcher** [comment]
Thanks for opening this @leewillis77. I've got a PR ready to merge!
