### ISSUE TITLE
Developer Experience

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/block-development-examples#8]
I went through the process of [creating a new example](https://github.com/wordpress-juanmaguitar/gutenberg-examples-2023/blob/trunk/CONTRIBUTIONS.md#adding-a-new-example-to-this-repo) by running `npm run create-example` and for the most part it was a easy and straightforward process. 

The only feedback I would give is that the step of choosing the tags was a little confusing for me. This is mostly because I didn't fully read the instructions and pressed `enter` to select a tag which confirmed my choices 🤦 . I would say that perhaps we need to have the tags in alphabetical order as they seemed random to me during my second try.

This is great tool for copying existing plugins in the repo and this coupled with a create-block template cover all of options for creating new examples.

**Comment by juanmaguitar** [comment]
@ryanwelcher I think we can close this issue

**Comment by ryanwelcher** [comment]
Closing as resolved.
