### ISSUE TITLE
Tutorial: Build your first block  - repair destination of link 

### ISSUE THREAD

**Issue by silverhoopedge** [WordPress/block-development-examples#83]
in entry-meta "improve it on github" text does not link to github.
`<p class="external-link"><a href="">Improve it on GitHub<span class="screen-reader-text">: Tutorial: Build your first block</span></a></p>`

**Comment by juanmaguitar** [comment]
This Issue has already been reported at https://github.com/WordPress/wporg-developer/issues/438 and https://github.com/WordPress/Documentation-Issue-Tracker/issues/1402
