### ISSUE TITLE
 Tutorial: Build your first block  - confusion about instruction

### ISSUE THREAD

**Issue by silverhoopedge** [WordPress/block-development-examples#84]
create a folder” – I am not sure I understand the purpose - I did not do this step and the tutorial worked okay.
_"Therefore, create a new directory (folder) on your computer called “Block Tutorial”_

“line 9” — this is relative, after a few file edits, the code referenced was not on line 9 for me 
_"So open up the file and add the following section after the example in line 9."_

**Comment by juanmaguitar** [comment]
cc: @ndiego

**Comment by ndiego** [comment]
Thanks @silverhoopedge, I have created a PR to address these items in https://github.com/WordPress/gutenberg/pull/57403
