### ISSUE TITLE
Improve the readability of the "Conventions for examples" wiki page

### ISSUE THREAD

**Issue by ndiego** [WordPress/block-development-examples#98]
I have found the [06 Conventions for examples](https://github.com/WordPress/block-development-examples/wiki/06-Conventions-for-examples) a bit challenging to read/parse, and I think it could be improved with some additional formatting and more context. I found myself struggling to follow it when trying to add a new block to the repo.

@juanmaguitar I am happy to take this on but I wanted to flag it before I did so.

**Comment by juanmaguitar** [comment]
Thanks for this feedback @ndiego 
Happy for you to take on this task and also happy to answer any questions on these conventions.

**Comment by ndiego** [comment]
I completed a first pass, but it could still probably be flushed out a bit more. I am going to close this issue out for now, but as I add examples in the future, I'll update the guide with anything else I think is warranted.

**Comment by juanmaguitar** [comment]
Thanks a lot for revamping this page, @ndiego 
It's much more clear now 🥳
